--- 
install: pip install -r requirements.txt
language: python
python: 
- "2.7"

# Run unit tests
script: 
- nosetests-2.7 wtframework/wtf/tests/ -a '!noci'
- nosetests-2.7 wtframework/wtf/data/tests/ -a '!noci'
- nosetests-2.7 wtframework/wtf/testobjects/tests/ -a '!noci'
- nosetests-2.7 wtframework/wtf/utils/tests/ -a '!noci'
- nosetests-2.7 wtframework/wtf/web/tests/ -a '!noci'

# Encrypted ENV var that contains API key to Sauce open source account.
env: 
  global: 
    secure: |-
      aGhXR6Cz33zEDq1I6xhiBShON2AJywMSL0vubVRmTkL8bS3QdKIeCnWcAU6j
      CBobRjQ+OLC4TLEe4EzZxc2GlwSe6NtFTk21AtwoBqLQSQE72JDhagsWr7om
      sVs3MVtqn8vDGUHDFS1b1UE8YNED2FSHlQNZT8DzKyeQjBMHzew=
